[package]
name = "cbor"
version = "0.1.0"
authors = ["martijnswaagman <martijn@swaagman.online>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_cbor = "0.11.1"
serde_json = "1.0"
